#!/usr/bin/env bash
#Write a Bash script that change the localhost IP and facebook.com IP
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '1 a 8.8.8.8 \t facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
